name: 'opencloudtool CLI Github Action'
description: 'GitHub Action for opencloudtool CLI'
author: 'opencloudtool'

branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  command:
    description: 'The opencloudtool CLI command to run'
    required: true
  working-directory:
    description: 'The working directory to run the command in'
    required: true
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Install `oct-cli`
      shell: bash
      run: curl -LsSf https://repo.opencloudtool.com/install.sh | sh

    - name: Run opencloudtool Command
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        oct-cli ${{ inputs.command }}
