name: Update Main Version

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Tag and push new target
        run: |
          MAJOR_VERSION=$(echo ${{ github.event.release.tag_name }} | cut -d. -f1)

          echo "Using major version: $MAJOR_VERSION"

          git tag -f $MAJOR_VERSION ${{ github.event.release.tag_name }}
          git push origin $MAJOR_VERSION --force
